local T = require("testlib")
local F = require("fixtures")
local L = require("agent.launcher")

T.test("parses node versions and picks the newest usable one", function()
  T.deepEq({ L.parseVersion("v24.11.1\n") }, { 24, 11, 1 })
  T.eq(L.parseVersion("nonsense"), nil)
  T.eq(L.pick({ { path = "/usr/local/bin/node", major = 10 }, { path = "/nvm/v24/bin/node", major = 24 }, { path = "/nvm/v22/bin/node", major = 22 } }), "/nvm/v24/bin/node")
  T.eq(L.pick({ { path = "/old", major = 18 } }), nil)
end)

T.test("candidates include env, nvm, volta, homebrew and system paths", function()
  local list = L.candidates({ ASEPRITE_AGENT_NODE = "/custom/node" }, "/h")
  T.eq(list[1], "/custom/node")
  local joined = table.concat(list, "\n")
  for _, p in ipairs{ "/h/.volta/bin/node", "/opt/homebrew/bin/node", "/usr/local/bin/node" } do
    T.eq(joined:find(p, 1, true) ~= nil, true, p)
  end
end)

T.test("findNode finds a real Node 20+ on this machine", function()
  local node = L.findNode({})
  T.eq(node ~= nil, true)
  local p = io.popen('"' .. node .. '" -v')
  local major = L.parseVersion(p:read("a"))
  p:close()
  T.eq(major >= 20, true)
end)

T.test("pidAlive tells live processes from dead ones", function()
  local p = io.popen("echo $PPID")
  local pid = tonumber(p:read("l"))
  p:close()
  T.eq(L.pidAlive(pid), true)
  T.eq(L.pidAlive(999999), false)
  T.eq(L.pidAlive(nil), false)
end)

T.test("the start command runs detached with a log and quotes paths", function()
  local cmd = L.startCommand("/a b/node", "/ext dir/bridge/bridge.mjs", "/h/.aseprite-agent/bridge.log")
  T.eq(cmd, "nohup '/a b/node' '/ext dir/bridge/bridge.mjs' >> '/h/.aseprite-agent/bridge.log' 2>&1 &")
  T.eq(L.startCommand("/x/$HOME`id`/node", "s", "l"), "nohup '/x/$HOME`id`/node' 's' >> 'l' 2>&1 &", "no shell expansion inside single quotes")
  T.eq(L.startCommand("/it's/node", "s", "l"), "nohup '/it'\\''s/node' 's' >> 'l' 2>&1 &")
end)

T.test("bridgeScript finds bridge/bridge.mjs inside the plugin folder", function()
  local dir = F.unique("plugin")
  app.fs.makeAllDirectories(app.fs.joinPath(dir, "bridge"))
  T.eq(L.bridgeScript(dir), nil)
  local f = io.open(app.fs.joinPath(dir, "bridge", "bridge.mjs"), "w"); f:write("//"); f:close()
  T.eq(L.bridgeScript(dir), app.fs.joinPath(dir, "bridge", "bridge.mjs"))
end)

T.test("an explicitly chosen Node 20+ wins over newer ones found elsewhere", function()
  local home = os.getenv("HOME")
  local v22 = home .. "/.nvm/versions/node/v22.17.1/bin/node"
  if not app.fs.isFile(v22) then return end
  T.eq(L.findNode({ preferred = v22 }), v22)
end)

T.test("isBridgePid only accepts processes running bridge.mjs", function()
  local p = io.popen("echo $PPID")
  local aseprite = tonumber(p:read("l"))
  p:close()
  T.eq(L.isBridgePid(aseprite), false, "a live process that isn't the bridge")
  local dir = F.unique("fake bridge")
  app.fs.makeAllDirectories(dir)
  local f = io.open(app.fs.joinPath(dir, "bridge.mjs"), "w"); f:write("setTimeout(() => {}, 20000)"); f:close()
  local node = L.findNode({})
  local h = io.popen("'" .. node .. "' '" .. app.fs.joinPath(dir, "bridge.mjs") .. "' >/dev/null 2>&1 & echo $!")
  local pid = tonumber(h:read("l"))
  h:close()
  T.eq(L.isBridgePid(pid), true)
  os.execute("kill " .. pid)
  T.eq(L.isBridgePid(999999), false)
end)
