local T = require("testlib")
local F = require("fixtures")
local palettes = require("agent.palettes")
local project = require("agent.project")

T.test("the palette list offers the sprite's palette, none, and Aseprite's built-in palettes", function()
  F.closeAll()
  local s = F.rgbSprite()
  local list = palettes.list(s)
  T.eq(list[1].label, "Current sprite palette (" .. #s.palettes[1] .. " colors)")
  T.eq(list[2].label, "None")
  local db32
  for _, e in ipairs(list) do if e.id == "DB32" then db32 = e end end
  T.eq(db32 ~= nil, true, "DB32 is among the built-in palettes")
  T.eq(#palettes.load(db32, s), 32)
  T.eq(palettes.load(list[2], s), nil)
  T.eq(#palettes.load(list[1], s), #s.palettes[1])
end)

T.test("with no sprite, the current-palette entry is left out", function()
  F.closeAll()
  T.eq(palettes.list(nil)[1].label, "None")
end)

local root = F.unique("brief tests ")
app.fs.makeAllDirectories(root)
project.create(root, { resolution = "32x32", light = "top-left", notes = "Cozy" })

T.test("the project palette is saved as palette.gpl and reads back", function()
  local pal = Palette(2)
  pal:setColor(0, Color{ r = 255, g = 128, b = 64 })
  pal:setColor(1, Color{ r = 0, g = 0, b = 0 })
  project.savePalette(root, pal)
  local back = Palette{ fromFile = app.fs.joinPath(root, ".artproject", "palette.gpl") }
  T.eq(#back, 2)
  T.eq(back:getColor(0).green, 128)
end)

T.test("readBrief returns the template fields; writeBrief round-trips them", function()
  local b = project.readBrief(root)
  T.eq(b.resolution, "32x32")
  T.eq(b.light, "top-left")
  T.eq(b.palette, "")
  T.eq(b.notes, "Cozy")
  T.eq(b.handEdited, false)
  b.light = "from the right"
  project.writeBrief(root, b)
  T.eq(project.readBrief(root).light, "from the right")
end)

T.test("a hand-edited brief is detected so the settings dialog won't overwrite it", function()
  local path = app.fs.joinPath(root, ".artproject", "brief.md")
  local f = io.open(path, "a"); f:write("\nExtra paragraph written by hand.\n"); f:close()
  T.eq(project.readBrief(root).handEdited, true)
end)

T.test("openCommand builds the platform's open command, quoting the path", function()
  T.eq(project.openCommand("/a b/c", "Darwin"), 'open "/a b/c"')
  T.eq(project.openCommand("/a b/c", "Linux"), 'xdg-open "/a b/c"')
  T.eq(project.openCommand("C:\\a b", "Windows"), 'start "" "C:\\a b"')
end)

T.test("describe names the chosen palette for the brief", function()
  F.closeAll()
  local s = F.rgbSprite("pal.aseprite")
  T.eq(palettes.describe({ id = "DB32", label = "DB32" }, Palette{ fromResource = "DB32" }, s), "DB32 (32 colors)")
  T.eq(palettes.describe({ current = true }, Palette(4), s), "From pal.aseprite (4 colors)")
  T.eq(palettes.describe({ none = true }, nil, s), "")
end)

T.test("clearMemory resets memory.md to its header", function()
  local path = app.fs.joinPath(root, ".artproject", "memory.md")
  local f = io.open(path, "a"); f:write("- Hero uses a 2px outline\n"); f:close()
  project.clearMemory(root)
  f = io.open(path, "r"); local text = f:read("a"); f:close()
  T.eq(text:find("2px outline", 1, true), nil)
  T.eq(text:find("# Project memory", 1, true) ~= nil, true)
end)
