local T = require("testlib")
local ChatModel = require("agent.chat_model")

T.test("consecutive agent deltas merge into one item", function()
  local m = ChatModel.new()
  m:addUser("hi")
  m:appendAgent("Hel")
  m:appendAgent("lo")
  T.deepEq(m.items, { { kind = "user", text = "hi" }, { kind = "agent", text = "Hello" } })
end)

T.test("activity splits agent text into separate items", function()
  local m = ChatModel.new()
  m:appendAgent("Let me look.")
  m:addActivity("Looked at knight.aseprite")
  m:appendAgent("The outline is thick.")
  T.eq(#m.items, 3)
  T.eq(m.items[3].kind, "agent")
end)

T.test("endTurn starts a fresh agent item next time", function()
  local m = ChatModel.new()
  m:appendAgent("a")
  m:endTurn()
  m:appendAgent("b")
  T.eq(#m.items, 2)
end)

T.test("errors include the hint on a new line", function()
  local m = ChatModel.new()
  m:addError("Claude Code isn't logged in.", "Run `claude` and log in.")
  T.deepEq(m.items[1], { kind = "error", text = "Claude Code isn't logged in.\nRun `claude` and log in." })
  m:addError("plain", nil)
  T.eq(m.items[2].text, "plain")
end)

T.test("clear empties the chat", function()
  local m = ChatModel.new()
  m:addUser("x")
  m:clear()
  T.eq(#m.items, 0)
end)

T.test("a new agent item drops leading blank lines (text after a tool call)", function()
  local m = ChatModel.new()
  m:appendAgent("Let me look.")
  m:addActivity("Looked at a")
  m:appendAgent("\n\n")
  m:appendAgent("It reads well.")
  T.eq(m.items[3].text, "It reads well.")
end)

T.test("sendAction: send when idle, reject a typed follow-up while busy, stop only when the entry is empty", function()
  T.eq(ChatModel.sendAction(false, "hi"), "send")
  T.eq(ChatModel.sendAction(false, "   "), "ignore")
  T.eq(ChatModel.sendAction(true, "follow-up"), "reject_busy")
  T.eq(ChatModel.sendAction(true, ""), "stop")
end)

T.test("approvals queue, resolve in order, and cancel at end of turn", function()
  local m = ChatModel.new()
  m:addApproval("a1", "Add layer \"A\"")
  m:addApproval("a2", "Add layer \"B\"")
  T.eq(m:pendingApproval().id, "a1")
  m:resolveApproval("a1", true)
  T.eq(m:pendingApproval().id, "a2")
  m:endTurn()
  T.eq(m:pendingApproval(), nil)
  T.eq(m.items[1].state, "applied")
  T.eq(m.items[2].state, "cancelled")
  m:resolveApproval("a2", true)
  T.eq(m.items[2].state, "cancelled", "late answers don't change a cancelled card")
end)

T.test("sendAction with a pending approval: Enter denies, typing is rejected", function()
  T.eq(ChatModel.sendAction(true, "", true), "deny")
  T.eq(ChatModel.sendAction(true, "wait", true), "reject_busy")
  T.eq(ChatModel.sendAction(true, "", false), "stop")
end)
