local T = require("testlib")
local F = require("fixtures")
local edit = require("agent.tools.edit")
local color = require("agent.tools.color")
local pc = app.pixelColor

T.test("parseHex reads #rrggbb and #rrggbbaa and rejects junk", function()
  T.deepEq({ color.parseHex("#0a141e") }, { 10, 20, 30, 255 })
  T.deepEq({ color.parseHex("#0A141E80") }, { 10, 20, 30, 128 })
  T.errors(function() color.parseHex("red") end, "Invalid color 'red'; use #rrggbb or #rrggbbaa.")
end)

T.test("references are non-aseprite tabs; unsaved sprites are editable", function()
  F.closeAll()
  local ref = Sprite(2, 2)
  ref:saveAs(app.fs.joinPath(F.tmp, "ref.png"))
  T.eq(edit.isReference(ref), true)
  local unsaved = Sprite(2, 2)
  T.eq(edit.isReference(unsaved), false)
  app.sprite = ref
  T.errors(function() edit.editableSprite() end, "'ref.png' is a reference image tab; it is read-only.")
end)

T.test("drawableLayer rejects groups and locked layers", function()
  F.closeAll()
  local s = F.rgbSprite()
  local g = s:newGroup()
  g.name = "Grp"
  local locked = s:newLayer()
  locked.name = "Locked"
  locked.isEditable = false
  T.errors(function() edit.drawableLayer(s, "Grp") end, "Layer 'Grp' is a group; name one of its layers.")
  T.errors(function() edit.drawableLayer(s, "Locked") end, "Layer 'Locked' is locked.")
  T.eq(edit.drawableLayer(s, "Body").name, "Body")
end)

T.test("transaction is one undo step and restores the active sprite", function()
  F.closeAll()
  local s = F.rgbSprite()
  local other = Sprite(2, 2)
  app.sprite = other
  edit.transaction(s, "test", function()
    local img = edit.canvasImage(s, s.layers[1], s.frames[1])
    img:drawPixel(3, 2, pc.rgba(0, 0, 255, 255))
    edit.commit(s, s.layers[1], s.frames[1], img)
    s:newLayer().name = "Extra"
  end)
  T.eq(app.sprite == other, true, "active sprite restored")
  T.eq(F.px(s, 3, 2, "Body"), pc.rgba(0, 0, 255, 255))
  T.eq(#s.layers, 2)
  app.sprite = s
  app.undo()
  T.eq(F.px(s, 3, 2, "Body"), 0)
  T.eq(#s.layers, 1)
  T.eq(F.px(s, 0, 0, "Body"), pc.rgba(255, 0, 0, 255), "earlier content untouched by the undo")
end)

T.test("a failing transaction rolls back and re-raises", function()
  F.closeAll()
  local s = F.rgbSprite()
  T.errors(function()
    edit.transaction(s, "boom", function()
      local img = edit.canvasImage(s, s.layers[1], s.frames[1])
      img:drawPixel(2, 2, pc.rgba(1, 1, 1, 255))
      edit.commit(s, s.layers[1], s.frames[1], img)
      error("boom", 0)
    end)
  end, "boom")
  T.eq(F.px(s, 2, 2, "Body"), 0)
end)

T.test("pixelValue maps colors per color mode", function()
  F.closeAll()
  local rgb = F.rgbSprite()
  T.eq(edit.pixelValue(rgb, "#0a141e"), pc.rgba(10, 20, 30, 255))
  T.eq(edit.pixelValue(rgb, "."), 0)
  local gray = Sprite(2, 2, ColorMode.GRAYSCALE)
  T.eq(pc.grayaV(edit.pixelValue(gray, "#ffffff")), 255)
  local idx = Sprite(2, 2, ColorMode.INDEXED)
  idx.palettes[1]:resize(3)
  idx.palettes[1]:setColor(2, Color{ r = 10, g = 20, b = 30, a = 255 })
  T.eq(edit.pixelValue(idx, "#0a141e"), 2)
  T.eq(edit.pixelValue(idx, "."), idx.transparentColor)
  T.errors(function() edit.pixelValue(idx, "#123456") end, "#123456 is not in the palette")
end)

T.test("canvasImage covers the whole canvas even when the cel is smaller or missing", function()
  F.closeAll()
  local s = F.rgbSprite()
  local l = s:newLayer()
  l.name = "Empty"
  local img = edit.canvasImage(s, l, s.frames[1])
  T.eq(img.width, 4)
  T.eq(img.height, 3)
  T.eq(img:getPixel(0, 0), 0)
end)

T.test("int converts JSON floats", function()
  T.eq(math.type(edit.int(F.decode({ n = 3 }).n)), "integer")
  T.eq(edit.int(2.0), 2)
end)

F.closeAll()
