local T = require("testlib")
local F = require("fixtures")
local tools = require("agent.tools")
local sprites = require("agent.tools.sprites")
local project = require("agent.project")
local pc = app.pixelColor

local function call(name, args) return tools.dispatch(name, F.decode(args)) end
local RED, GREEN, BLUE = pc.rgba(255, 0, 0, 255), pc.rgba(0, 255, 0, 255), pc.rgba(0, 0, 255, 255)

T.test("dither paints only opaque pixels by default, with the checker pattern", function()
  F.closeAll()
  local s = F.rgbSprite() -- red (0,0), green (1,0)
  local r = call("dither", { layer = "Body", colorA = "#ff0000", colorB = "#0000ff", amount = 0.5, pattern = "checker" })
  T.eq(r.ok, true, r.error)
  T.eq(F.px(s, 0, 0, "Body"), BLUE)
  T.eq(F.px(s, 1, 0, "Body"), RED)
  T.eq(F.px(s, 2, 0, "Body"), 0, "transparent pixels untouched")
  app.undo()
  T.eq(F.px(s, 0, 0, "Body"), RED)
end)

T.test("FX refuse non-RGB sprites", function()
  F.closeAll()
  app.sprite = Sprite(2, 2, ColorMode.INDEXED)
  T.eq(call("pixel_perfect", { layer = "Layer 1" }).error, "Effects work on RGB sprites. Convert with Sprite > Color Mode > RGB first.")
end)

T.test("gradient_fill fills the region, linear, without dither", function()
  F.closeAll()
  local s = F.rgbSprite()
  local r = call("gradient_fill", { layer = "Body", colors = { "#000000", "#ffffff" }, region = { x = 0, y = 1, w = 4, h = 1 } })
  T.eq(r.ok, true, r.error)
  T.eq(F.px(s, 0, 1, "Body"), pc.rgba(0, 0, 0, 255))
  T.eq(F.px(s, 3, 1, "Body"), pc.rgba(255, 255, 255, 255))
  T.eq(F.px(s, 0, 0, "Body"), RED, "outside the region untouched")
end)

T.test("pixel_perfect turns an L into a diagonal across all frames", function()
  F.closeAll()
  local s = Sprite(3, 2)
  app.sprite = s
  local img = s.cels[1].image:clone()
  img:drawPixel(0, 0, RED); img:drawPixel(1, 0, RED); img:drawPixel(1, 1, RED)
  s.cels[1].image = img
  s:newFrame(1)
  local r = call("pixel_perfect", { layer = "Layer 1", allFrames = true })
  T.eq(r.ok, true, r.error)
  T.eq(r.data.changed, 2)
  T.eq(F.px(s, 1, 0, "Layer 1", 1), 0)
  T.eq(F.px(s, 1, 0, "Layer 1", 2), 0)
  app.undo()
  T.eq(F.px(s, 1, 0, "Layer 1", 2), RED, "one undo for all frames")
end)

T.test("snap_to_palette uses the sprite palette, or explains a missing project palette", function()
  F.closeAll()
  local s = F.rgbSprite()
  local pal = Palette(2)
  pal:setColor(0, Color{ r = 0, g = 0, b = 0 })
  pal:setColor(1, Color{ r = 250, g = 10, b = 10 })
  s:setPalette(pal)
  local r = call("snap_to_palette", { palette = "sprite" })
  T.eq(r.ok, true, r.error)
  T.eq(F.px(s, 0, 0, "Body"), pc.rgba(250, 10, 10, 255))
  T.eq(r.data.changed, 2)
  sprites.projectRoot = nil
  T.eq(call("snap_to_palette", {}).error, "This project has no palette. Pick one in Project settings, or use palette = \"sprite\".")
end)

T.test("snap_to_palette reads the project's palette.gpl", function()
  F.closeAll()
  local root = F.unique("fx proj ")
  app.fs.makeAllDirectories(root)
  if not app.fs.isDirectory(app.fs.joinPath(root, ".artproject")) then project.create(root, {}) end
  local pal = Palette(1)
  pal:setColor(0, Color{ r = 0, g = 0, b = 255 })
  project.savePalette(root, pal)
  sprites.projectRoot = root
  local s = F.rgbSprite()
  local r = call("snap_to_palette", { layer = "Body" })
  T.eq(r.ok, true, r.error)
  T.eq(F.px(s, 0, 0, "Body"), BLUE)
  sprites.projectRoot = nil
end)

T.test("selout darkens the outline toward the fill it borders", function()
  F.closeAll()
  local s = Sprite(5, 5)
  app.sprite = s
  local img = s.cels[1].image:clone()
  img:clear(pc.rgba(0, 0, 0, 255))
  for y = 1, 3 do for x = 1, 3 do img:drawPixel(x, y, pc.rgba(200, 100, 50, 255)) end end
  s.cels[1].image = img
  local r = call("selout", { layer = "Layer 1", darken = 0.5 })
  T.eq(r.ok, true, r.error)
  T.eq(F.px(s, 0, 2, "Layer 1"), pc.rgba(100, 50, 25, 255))
  T.eq(F.px(s, 0, 0, "Layer 1"), pc.rgba(100, 50, 25, 255), "corners use the diagonal fill")
  T.eq(F.px(s, 2, 2, "Layer 1"), pc.rgba(200, 100, 50, 255), "fill untouched")
end)

T.test("layer_style overlay, stroke and shadow", function()
  F.closeAll()
  local s = F.rgbSprite()
  T.eq(call("layer_style", { layer = "Body", style = "overlay", color = "#0000ff", amount = 1 }).ok, true)
  T.eq(F.px(s, 0, 0, "Body"), BLUE)
  app.undo()
  local st = call("layer_style", { layer = "Body", style = "stroke", color = "#0000ff", width = 1 })
  T.eq(st.ok, true, st.error)
  T.eq(st.data.newLayer, "Body stroke")
  T.eq(s.layers[1].name, "Body stroke", "stroke sits below the layer")
  T.eq(F.px(s, 2, 0, "Body stroke"), BLUE)
  T.eq(F.px(s, 0, 1, "Body stroke"), BLUE)
  T.eq(F.px(s, 2, 1, "Body stroke"), 0, "4-neighbour stroke, no diagonal corner")
  T.eq(F.px(s, 0, 0, "Body stroke"), 0, "not under the art")
  app.undo()
  T.eq(#s.layers, 1, "one undo removes the stroke layer")
  local sh = call("layer_style", { layer = "Body", style = "shadow", color = "#000000", offsetX = 1, offsetY = 1 })
  T.eq(sh.ok, true, sh.error)
  T.eq(F.px(s, 1, 1, "Body shadow"), pc.rgba(0, 0, 0, 255))
  T.eq(F.px(s, 2, 1, "Body shadow"), pc.rgba(0, 0, 0, 255))
end)

F.closeAll()

T.test("effects follow the exact selection shape, not its bounding box", function()
  F.closeAll()
  local s = F.rgbSprite()
  local sel = Selection(Rectangle(0, 1, 1, 1))
  sel:add(Rectangle(2, 1, 1, 1))
  s.selection = sel
  T.eq(call("gradient_fill", { layer = "Body", colors = { "#000000", "#ffffff" } }).ok, true)
  T.eq(F.px(s, 1, 1, "Body"), 0, "the gap inside the selection bounds stays empty")
  T.eq(F.px(s, 0, 1, "Body") ~= 0, true)
end)

T.test("shadow respects the region, and stroke layers stay inside the source's group", function()
  F.closeAll()
  local s = F.rgbSprite()
  local sh = call("layer_style", { layer = "Body", style = "shadow", color = "#000000", offsetX = 0, offsetY = 1, region = { x = 0, y = 0, w = 1, h = 1 } })
  T.eq(sh.ok, true, sh.error)
  T.eq(F.px(s, 0, 1, "Body shadow") ~= 0, true)
  T.eq(F.px(s, 1, 1, "Body shadow"), 0, "pixels outside the region cast no shadow")
  F.closeAll()
  local s2 = F.rgbSprite()
  local g = s2:newGroup()
  g.name = "Char"
  s2.layers[1].parent = g
  local st = call("layer_style", { layer = "Body", style = "stroke", color = "#0000ff" })
  T.eq(st.ok, true, st.error)
  local stroke
  for _, l in ipairs(g.layers) do if l.name == "Body stroke" then stroke = l end end
  T.eq(stroke ~= nil, true, "stroke layer is inside the group")
end)

T.test("snap_to_palette with a fully transparent palette explains itself", function()
  F.closeAll()
  local s = F.rgbSprite()
  local pal = Palette(1)
  pal:setColor(0, Color{ r = 0, g = 0, b = 0, a = 0 })
  s:setPalette(pal)
  T.eq(call("snap_to_palette", { palette = "sprite" }).error, "That palette has no opaque colors to snap to.")
end)
