local T = require("testlib")
local ChatModel = require("agent.chat_model")

T.test("consecutive agent deltas merge into one item", function()
  local m = ChatModel.new()
  m:addUser("hi")
  m:appendAgent("Hel")
  m:appendAgent("lo")
  T.deepEq(m.items, { { kind = "user", text = "hi" }, { kind = "agent", text = "Hello" } })
end)

T.test("activity splits agent text into separate items", function()
  local m = ChatModel.new()
  m:appendAgent("Let me look.")
  m:addActivity("Looked at knight.aseprite")
  m:appendAgent("The outline is thick.")
  T.eq(#m.items, 3)
  T.eq(m.items[3].kind, "agent")
end)

T.test("endTurn starts a fresh agent item next time", function()
  local m = ChatModel.new()
  m:appendAgent("a")
  m:endTurn()
  m:appendAgent("b")
  T.eq(#m.items, 2)
end)

T.test("errors include the hint on a new line", function()
  local m = ChatModel.new()
  m:addError("Claude Code isn't logged in.", "Run `claude` and log in.")
  T.deepEq(m.items[1], { kind = "error", text = "Claude Code isn't logged in.\nRun `claude` and log in." })
  m:addError("plain", nil)
  T.eq(m.items[2].text, "plain")
end)

T.test("clear empties the chat", function()
  local m = ChatModel.new()
  m:addUser("x")
  m:clear()
  T.eq(#m.items, 0)
end)
