local T = require("testlib")
local F = require("fixtures")
local tools = require("agent.tools")

local function call(name, args) return tools.dispatch(name, F.decode(args)) end

T.test("layer_ops add, rename, set, move - each one undo step", function()
  F.closeAll()
  local s = F.rgbSprite()
  T.eq(call("layer_ops", { action = "add", name = "Shading" }).ok, true)
  T.eq(s.layers[2].name, "Shading")
  T.eq(call("layer_ops", { action = "add", name = "Shading" }).error, "A layer named 'Shading' already exists.")
  T.eq(call("layer_ops", { action = "rename", layer = "Shading", name = "Shade" }).ok, true)
  local r = call("layer_ops", { action = "set", layer = "Shade", visible = false, opacity = 128, blendMode = "multiply" })
  T.eq(r.ok, true, r.error)
  T.eq(s.layers[2].isVisible, false)
  T.eq(s.layers[2].opacity, 128)
  T.eq(s.layers[2].blendMode, BlendMode.MULTIPLY)
  app.undo()
  T.eq(s.layers[2].opacity, 255)
  T.eq(s.layers[2].isVisible, true)
  T.eq(call("layer_ops", { action = "move", layer = "Shade", toIndex = 1 }).ok, true)
  T.eq(s.layers[1].name, "Shade")
end)

T.test("layer_ops reports missing arguments plainly", function()
  F.closeAll()
  F.rgbSprite()
  T.eq(call("layer_ops", { action = "add" }).error, "layer_ops add needs 'name'.")
  T.eq(call("layer_ops", { action = "set", name = "x" }).error, "layer_ops set needs 'layer'.")
  T.eq(call("layer_ops", { action = "set", layer = "Body", blendMode = "sparkle" }).error, "Unknown blend mode 'sparkle'.")
end)

T.test("ensure_draft_layer creates the draft layer once", function()
  F.closeAll()
  local s = F.rgbSprite()
  local r = call("ensure_draft_layer", {})
  T.eq(r.ok, true, r.error)
  T.eq(r.data.created, true)
  T.eq(s.layers[#s.layers].name, "AI Draft")
  T.eq(s.layers[#s.layers].opacity, 102)
  T.eq(call("ensure_draft_layer", {}).data.created, false)
  T.eq(#s.layers, 2)
end)

T.test("frame_ops add_empty, duplicate, set_duration, add_tag", function()
  F.closeAll()
  local s = F.rgbSprite()
  local d = call("frame_ops", { action = "duplicate", frame = 1 })
  T.eq(d.ok, true, d.error)
  T.eq(#s.frames, 2)
  T.eq(F.px(s, 0, 0, "Body", 2), F.px(s, 0, 0, "Body", 1))
  local e = call("frame_ops", { action = "add_empty" })
  T.eq(e.data.frame, 3)
  T.eq(s.layers[1]:cel(3), nil)
  T.eq(call("frame_ops", { action = "set_duration", frame = 1, toFrame = 3, durationMs = 150 }).ok, true)
  T.eq(math.floor(s.frames[3].duration * 1000 + 0.5), 150)
  T.eq(call("frame_ops", { action = "add_tag", name = "idle", frame = 1, toFrame = 2 }).ok, true)
  T.eq(s.tags[1].name, "idle")
  T.eq(s.tags[1].toFrame.frameNumber, 2)
  app.undo()
  T.eq(#s.tags, 0)
  T.eq(call("frame_ops", { action = "set_duration", frame = 9, durationMs = 100 }).error, "Frame 9 does not exist (sprite has 3 frames).")
end)
