local T = require("testlib")
local F = require("fixtures")
local tools = require("agent.tools")
local pc = app.pixelColor

local function call(name, args) return tools.dispatch(name, F.decode(args)) end

T.test("annotate draws on a new top Agent Notes layer, clipped to the canvas", function()
  F.closeAll()
  local s = F.rgbSprite()
  local r = call("annotate", { shapes = { { type = "dot", x = 1, y = 1 }, { type = "line", x = 0, y = 2, x2 = 10, y2 = 2 } } })
  T.eq(r.ok, true, r.error)
  T.eq(r.data.marks, 2)
  local top = s.layers[#s.layers]
  T.eq(top.name, "Agent Notes")
  T.eq(F.px(s, 1, 1, "Agent Notes"), pc.rgba(255, 59, 48, 255))
  T.eq(F.px(s, 3, 2, "Agent Notes"), pc.rgba(255, 59, 48, 255))
  T.eq(F.px(s, 1, 1, "Body"), 0, "artist's layer untouched")
  app.undo()
  T.eq(#s.layers, 1, "one undo removes notes layer and marks")
end)

T.test("annotate clear wipes previous marks on that frame", function()
  F.closeAll()
  local s = F.rgbSprite()
  call("annotate", { shapes = { { type = "dot", x = 0, y = 0 } } })
  call("annotate", { clear = true, color = "#00ff00", shapes = { { type = "dot", x = 3, y = 0 } } })
  T.eq(F.px(s, 0, 0, "Agent Notes"), 0)
  T.eq(F.px(s, 3, 0, "Agent Notes"), pc.rgba(0, 255, 0, 255))
end)

T.test("annotate needs the right fields per shape", function()
  F.closeAll()
  F.rgbSprite()
  T.eq(call("annotate", { shapes = { { type = "line", x = 0, y = 0 } } }).error, "A line needs x2 and y2.")
  T.eq(call("annotate", { shapes = { { type = "circle", x = 0, y = 0 } } }).error, "A circle needs r.")
end)

T.test("transform outline outside surrounds opaque pixels with the color", function()
  F.closeAll()
  local s = F.rgbSprite() -- red (0,0), green (1,0)
  local r = call("transform", { layer = "Body", action = "outline", color = "#000000" })
  T.eq(r.ok, true, r.error)
  T.eq(F.px(s, 0, 1, "Body"), pc.rgba(0, 0, 0, 255))
  T.eq(F.px(s, 2, 0, "Body"), pc.rgba(0, 0, 0, 255))
  T.eq(F.px(s, 2, 1, "Body"), 0, "diagonal neighbours are not outlined")
  T.eq(F.px(s, 0, 0, "Body"), pc.rgba(255, 0, 0, 255), "original pixels kept")
  app.undo()
  T.eq(F.px(s, 0, 1, "Body"), 0)
end)

T.test("transform outline inside recolors the edge pixels", function()
  F.closeAll()
  local s = F.rgbSprite()
  call("transform", { layer = "Body", action = "outline", place = "inside", color = "#0000ff" })
  T.eq(F.px(s, 0, 0, "Body"), pc.rgba(0, 0, 255, 255))
end)

T.test("transform flips the whole layer or a region", function()
  F.closeAll()
  local s = F.rgbSprite()
  call("transform", { layer = "Body", action = "flip_horizontal" })
  T.eq(F.px(s, 3, 0, "Body"), pc.rgba(255, 0, 0, 255))
  T.eq(F.px(s, 2, 0, "Body"), pc.rgba(0, 255, 0, 255))
  app.undo()
  call("transform", { layer = "Body", action = "flip_vertical", region = { x = 0, y = 0, w = 1, h = 3 } })
  T.eq(F.px(s, 0, 2, "Body"), pc.rgba(255, 0, 0, 255))
  T.eq(F.px(s, 1, 0, "Body"), pc.rgba(0, 255, 0, 255), "outside the region untouched")
end)
