local T = require("testlib")
local F = require("fixtures")
local prefs = require("agent.prefs")
local context = require("agent.context")

T.test("conversation ids are remembered per project, and the old single id migrates", function()
  local p = { conversationId = "old" }
  T.eq(prefs.getConversation(p, nil), "old")
  T.eq(p.conversationId, nil)
  prefs.setConversation(p, "/art/game", "g1")
  T.eq(prefs.getConversation(p, "/art/game"), "g1")
  T.eq(prefs.getConversation(p, nil), "old")
  prefs.setConversation(p, "/art/game", nil)
  T.eq(prefs.getConversation(p, "/art/game"), nil)
  T.eq(type(p.conversationsJson), "string")
  p.conversationsJson = "{broken"
  T.eq(prefs.getConversation(p, nil), nil, "corrupt preference is treated as empty")
end)

T.test("context describes the active sprite, frame, layer, selection and open tabs", function()
  F.closeAll()
  local s = F.rgbSprite("ctx.aseprite")
  s.selection = Selection(Rectangle(1, 0, 2, 2))
  local ctx = context.build(nil)
  T.eq(ctx.activeSprite, "ctx.aseprite")
  T.eq(ctx.frame, 1)
  T.eq(ctx.frameCount, 1)
  T.eq(ctx.layer, "Body")
  T.deepEq(ctx.selection, { x = 1, y = 0, w = 2, h = 2 })
  T.deepEq(ctx.openSprites, { "ctx.aseprite" })
  local rel = context.build(F.tmp)
  T.eq(rel.activeSprite, "ctx.aseprite", "project-relative inside the project root")
end)

T.test("context with no open sprite is just an empty tab list", function()
  F.closeAll()
  T.deepEq(context.build(nil), { openSprites = {} })
end)
